#! /bin/sh
#
# chkconfig: - 55 45
# description:	The redis-server daemon is a NoSQL service.
# processname: redis-server
# config: 
# pidfile: /var/run/redis.pid

# Standard LSB functions
#. /lib/lsb/init-functions

# Source function library.
. /etc/init.d/functions

REDIS_HOME=/local/apps/redis/bin
REDIS_CONF=/local/conf/redispair/redis1.conf
REDIS_LOG=/local/logs
REDIS_DATA=/local/data/redispair/redis1

PORT=7000
USER=root
OPTIONS=""

if [ ! -d $REDIS_DATA ];then
    mkdir -p $REDIS_DATA
fi

if [ ! -d $REDIS_LOG ];then
    mkdir -p $REDIS_LOG
fi

# Check that networking is up.
. /etc/sysconfig/network

if [ "$NETWORKING" = "no" ]
then
	exit 0
fi

RETVAL=0
prog="redis-server"
pidfile=${PIDFILE-/var/run/redis1.pid}
lockfile=${LOCKFILE-/var/lock/subsys/redis1}

start () {
	echo -n $"Starting $prog: "
	daemon --pidfile ${pidfile} $REDIS_HOME/redis-server $REDIS_CONF $OPTIONS
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch ${lockfile}
}
stop () {
	echo -n $"Stopping $prog: "
	killproc -p ${pidfile} $REDIS_HOME/redis-server
	RETVAL=$?
	echo
	if [ $RETVAL -eq 0 ] ; then
		rm -f ${lockfile} ${pidfile}
	fi
}

restart () {
        stop
        start
}


# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status -p ${pidfile} $REDIS_HOME/redis-server
	RETVAL=$?
	;;
  restart|reload|force-reload)
	restart
	;;
  condrestart|try-restart)
	[ -f ${lockfile} ] && restart || :
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart|try-restart}"
	RETVAL=2
        ;;
esac

exit $RETVAL
