#!/bin/bash

CONTACT=node01
PORT=6379
RF=1
action=$1

case "$action" in
	create)
		redis-trib.rb create --replicas $RF \
192.168.0.42:$PORT 192.168.0.15:$PORT 192.168.0.50:$PORT 192.168.0.17:$PORT 192.168.0.48:$PORT 192.168.0.19:$PORT \
192.168.0.20:$PORT 192.168.0.21:$PORT 192.168.0.22:$PORT 192.168.0.45:$PORT 192.168.0.24:$PORT 192.168.0.25:$PORT \
192.168.0.26:$PORT 192.168.0.27:$PORT 192.168.0.49:$PORT 192.168.0.29:$PORT 192.168.0.30:$PORT 192.168.0.31:$PORT 
	;;
	flush)
		fab remote_run:"printf 'flushall\n' | redis-cli -p $PORT" -R servers
	;;		
	clean)
		fab cleanup:redis -R servers
	;;
	check)
		redis-trib.rb check ${CONTACT}:${PORT}
	;;
	*)
		echo "Usage: `basename $0` create|flush|clean|check"
	    exit 1
esac
