#!/bin/bash

ACTION=${1:-"load"}
DB=${2:-"aerospike"}
MARK=${3:-"default"}
workload=${4:-"a"}
THREAD=${5:-"8"}
record=${6:-"4000000"}
RUNTIME=${7:-"10"}

SAVE=true
target=30000
NIC='eth0'
DEVICE='vda2'

case "$DB" in
	aerospike)
		PROC='asd'
	;;
	infinispan|cassandra)
		PROC='java'
	;;
	redis)
		PROC='redis-server'
	;;
	*)
	echo 'Invalid DB=$DB'
	exit 1
	;;
esac

cmd="fab run_test:$ACTION,workload=${workload},recordcount=${record},runtime=$RUNTIME,threads=$THREAD,target=${target},mark=$MARK,save=$SAVE --set db=$DB"
echo $cmd
$cmd &

if [[ "X$ACTION" == "Xrun" ]]; then
	cmd="fab monitorit:mark=$MARK,proc=$PROC,nic=$NIC,device=$DEVICE,duration=$RUNTIME,save=$SAVE --set db=$DB"
	echo $cmd
	$cmd &
fi
